version: "3"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:v1.6.0-beta
    container_name: bunkerweb
    ports:
      - "2:8080"
    environment:
      API_WHITELIST_IP: "127.0.0.0/24 10.20.30.0/24"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:v1.6.0-beta
    container_name: bw-scheduler
    depends_on:
      - bunkerweb
    volumes:
      - bw-data:/data
    environment:
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: "${WEB_UI_HOST}"
      MULTISITE: "yes"
      API_WHITELIST_IP: "127.0.0.0/24 10.20.30.0/24"
      SERVE_FILES: "no"
      USE_BUNKERNET: "no"
      USE_BLACKLIST: "no"
      USE_WHITELIST: "no"
      SEND_ANONYMOUS_REPORT: "no"
      USE_REAL_IP: "yes"
      REAL_IP_FROM: "10.0.0.0/8"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      COOKIE_FLAGS: ""
      COOKIE_AUTO_SECURE_FLAG: "no"
      KEEP_UPSTREAM_HEADERS: "*"
      ${WEB_UI_HOST}_USE_TEMPLATE: "ui"
      ${WEB_UI_HOST}_USE_REVERSE_PROXY: "yes"
      ${WEB_UI_HOST}_REVERSE_PROXY_URL: "/admin"
      ${WEB_UI_HOST}_REVERSE_PROXY_HOST: "http://bw-ui:7000"
      CUSTOM_CONF_HTTP_increase_server_names_hash_bucket_size: "server_names_hash_bucket_size 256;"
    restart: "unless-stopped"
    networks:
      - bw-universe

  bw-ui:
    image: bunkerity/bunkerweb-ui:v1.6.0-beta
    container_name: bw-ui
    ports:
      - "1:7000"
    volumes:
      - bw-data:/data
    environment:
      CHECK_PRIVATE_IP: "no"
      ALWAYS_REMEMBER: "yes"
    restart: "unless-stopped"
    networks:
      - bw-universe

  app1:
    image: nginxdemos/nginx-hello
    restart: "unless-stopped"
    networks:
      - bw-services

volumes:
  bw-data:


networks:
  bw-universe:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
